# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
# renovate: datasource=docker depName=ghcr.io/siderolabs/installer
talosVersion: v1.9.1
# renovate: datasource=docker depName=ghcr.io/siderolabs/kubelet
kubernetesVersion: v1.31.3

clusterName: home
endpoint: https://192.168.64.20:6443
domain: spyrja.internal

additionalApiServerCertSans: &sans
 - 127.0.0.1 # KubePrism
 - kubernetes.spyrja.internal
 
additionalMachineCertSans: *sans

cniConfig:
  name: none

nodes:
  - hostname: controller
    controlPlane: true
    ignoreHostname: true
    ipAddress: 192.168.64.21, 192.168.64.22, 192.168.64.23
    installDisk: /dev/nvme0n1
    machineSpec:
      useUKI: true
      secureboot: true
    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/gvisor
            - siderolabs/intel-ucode

controlPlane:
  networkInterfaces:
    - interface: enp44s0
      dhcp: true
      vip:
        ip: 192.168.64.20

  patches:
    # Cluster configuration
    - |-
      cluster:
        allowSchedulingOnControlPlanes: true
        controllerManager:
          extraArgs:
            bind-address: 0.0.0.0
        network:
          podSubnets:
            - 10.244.0.0/16
          serviceSubnets:
            - 10.96.0.0/16
        proxy:
          disabled: true
        scheduler:
          extraArgs:
            bind-address: 0.0.0.0

    # ETCD configuration
    # - |-
    #   cluster:
    #     etcd:
    #       extraArgs:
    #         listen-metrics-urls: http://0.0.0.0:2381
    #       advertisedSubnets:
    #         - 192.168.64.0/24

    # Enable K8s Talos API Access
    - |-
      machine:
        features:
          kubernetesTalosAPIAccess:
            enabled: true
            allowedRoles:
              - os:admin
            allowedKubernetesNamespaces:
              - system-upgrade

patches:

  # Set NTP server(s)
  - |-
    machine:
      time:
        disabled: false
        servers:
          - 192.168.64.1

  

  

  # Configure containerd
  # - |-
  #   machine:
  #     files:
  #       - op: create
  #         path: /etc/cri/conf.d/20-customization.part
  #         content: |-
  #           [plugins."io.containerd.grpc.v1.cri"]
  #             enable_unprivileged_ports = true
  #             enable_unprivileged_icmp = true
  #           [plugins."io.containerd.grpc.v1.cri".containerd]
  #             discard_unpacked_layers = false
  #           [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
  #             discard_unpacked_layers = false
